name: GoPostSubmit

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  # Common versions
  GO_VERSION: '1.20'
  GO_REQUIRED_MIN_VERSION: ''
  GOPATH: '/home/runner/work/multicluster-controlplane/multicluster-controlplane/go'
defaults:
  run:
    working-directory: go/src/open-cluster-management.io/multicluster-controlplane

jobs:
  image:
    name: image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/open-cluster-management.io/multicluster-controlplane
      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: install imagebuilder
        run: go install github.com/openshift/imagebuilder/cmd/imagebuilder@v1.2.4-0.20230309135844-a3c3f8358ca3
      - name: pull base image
        run: docker pull registry.access.redhat.com/ubi8/ubi-minimal:latest --platform=linux/${{ matrix.arch }}
      - name: image
        run: |
          IMAGE_TAG=latest-${{ matrix.arch }} \
          IMAGE_BUILD_EXTRA_FLAGS="--build-arg OS=linux --build-arg ARCH=${{ matrix.arch }}" \
            make image
      - name: push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login quay.io --username ${{ secrets.DOCKER_USER }} --password-stdin
          docker push quay.io/open-cluster-management/multicluster-controlplane:latest-${{ matrix.arch }}
  image-manifest:
    name: image manifest
    runs-on: ubuntu-latest
    needs: [ image ]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/open-cluster-management.io/multicluster-controlplane
      - name: create
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login quay.io --username ${{ secrets.DOCKER_USER }} --password-stdin
          docker manifest create quay.io/open-cluster-management/multicluster-controlplane:latest \
            quay.io/open-cluster-management/multicluster-controlplane:latest-amd64 \
            quay.io/open-cluster-management/multicluster-controlplane:latest-arm64
      - name: annotate
        run: |
          docker manifest annotate quay.io/open-cluster-management/multicluster-controlplane:latest \
            quay.io/open-cluster-management/multicluster-controlplane:latest-amd64 --arch amd64
          docker manifest annotate quay.io/open-cluster-management/multicluster-controlplane:latest \
            quay.io/open-cluster-management/multicluster-controlplane:latest-arm64 --arch arm64
      - name: push
        run: |
          docker manifest push quay.io/open-cluster-management/multicluster-controlplane:latest
